### ISSUE TITLE
ngCovervid not autoplaying on mobile

### ISSUE THREAD

**Issue by ivanbrens** [jfeigel/ngCovervid#5]
Any particular reason why this will not play on mobilie? 

 I am using chrome and safari on iPhone 6.

I have tested with my site and your demo site.

**Comment by jfeigel** [comment]
Apple disables autoplay on mobile:

> In Safari on iOS (for all devices, including iPad), where the user may be on a cellular network and be charged per data unit, preload and autoplay are disabled. No data is loaded until the user initiates it. This means the JavaScript play() and load() methods are also inactive until the user initiates playback, unless the play() or load() method is triggered by user action. In other words, a user-initiated Play button works, but an onLoad="play()" event does not.

https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html

You can either hide it for mobile or use the fallback image.
